### ISSUE TITLE
Add SPI pin and/or I2C select bridge

### ISSUE THREAD

**Issue by 3d-gussner** [prusa3d/PRUSA_Laser_filament_sensor#1]
As Prusa is planning to have 5 filament runout sensors on the MK3 MMU wouldn't it make sense to:
- add a solder bridge from ID_SEL (pin 8 PAT9125EL) to GND and VDD (3 sensors could be active in I2C mode at the same time)
  -  closed to VDD = HIGH I2C Slave ID (7-bit) 0x73
  -  closed to GND = LOW I2C Slave ID (7-bit) 0x75
  -  open = NC I2C Slave ID (7-bit) 0x79
- add additional PIN (ID_SEL) to the MMU stepper switch to use the PAT9125EL in SPI mode

Why don't use the MOTION pin 7 to detect "simple" motion?

**Comment by ok1hra** [comment]
Because motion pin provides too little information

**Comment by 3d-gussner** [comment]
@ok1hra Thanks for the info. I
Can you tell me what i am doing wrong opening the KiCad schematics i get:
The following libraries were not found:
 - \home\dan\kicad\hra\lib\ok1hra

**Comment by ok1hra** [comment]
Yes, this in the past use libraries you do not need, the used parts are inserted.
